#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Guardrail before cutting a release: fail if any feature/ or fix/ branch is
# not merged into develop.
# Usage: scripts/git-workflow/check_release.sh
set -eu

unmerged="$(git branch --no-merged develop | grep -E 'feature/|fix/' || true)"
if [ -n "$unmerged" ]; then
  echo "Release guardrail: these branches are not merged into develop:" >&2
  printf '%s\n' "$unmerged" >&2
  echo "Resolve them before creating a release/<version> branch." >&2
  exit 1
fi
echo "All feature/fix branches are merged into develop. Safe to cut a release."
