#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Remove a merged worktree and its branch.
# Usage: scripts/git-workflow/cleanup_worktree.sh <branch e.g. feature/foo>
set -eu

usage() {
  echo "Usage: $0 <branch e.g. feature/foo>" >&2
  exit 2
}

[ $# -eq 1 ] || usage
branch="$1"
worktree=".worktrees/$(printf '%s' "$branch" | tr '/' '-')"

git worktree remove "$worktree"
git branch -d "$branch"
echo "Removed worktree $worktree and branch $branch"
