#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Finish a feature/* or fix/* change: run project checks, publish the change
# branch, merge into develop, push develop, then clean up the worktree and
# branch (and remote if present).
# Usage: scripts/git-workflow/finish.sh <feature|fix> <name>
set -eu

usage() {
  echo "Usage: $0 <feature|fix> <name>" >&2
  exit 2
}

[ $# -eq 2 ] || usage
kind="$1"
name="$2"

case "$kind" in
  feature | fix) ;;
  *) usage ;;
esac

branch="$kind/$name"
worktree=".worktrees/$kind-$name"
CHECK_COMMAND="python -m unittest discover -s tests -v"

if ! git show-ref --verify --quiet "refs/heads/$branch"; then
  echo "finish: branch '$branch' does not exist." >&2
  exit 1
fi

if [ -d "$worktree" ]; then
  if [ -n "$(git -C "$worktree" status --porcelain)" ]; then
    echo "finish: worktree '$worktree' has uncommitted changes." >&2
    exit 1
  fi
fi

if [ -n "$CHECK_COMMAND" ]; then
  if [ -d "$worktree" ]; then
    (cd "$worktree" && sh -c "$CHECK_COMMAND")
  else
    echo "finish: no worktree at '$worktree'; running checks from repo root." >&2
    sh -c "$CHECK_COMMAND"
  fi
else
  echo "finish: no check_command configured in playbook.yaml; continuing without automated checks."
fi

# Publish the change branch first so local cleanup is not blocked by an
# outdated remote-tracking ref after the merge into develop.
git push -u origin "$branch"

git checkout develop
git pull --ff-only
git merge --no-ff "$branch" -m "Merge branch '$branch' into develop"
git push origin develop

if [ -d "$worktree" ]; then
  git worktree remove "$worktree"
fi
git branch -d "$branch"

if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  git push origin --delete "$branch"
fi

echo "Finished $branch. Merged into develop, pushed, and cleaned up."
