#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Create a fresh feature/, fix/, or release/ branch in a dedicated worktree from develop.
# Usage: scripts/git-workflow/new_worktree.sh <feature|fix|release> <name>
set -eu

usage() {
  echo "Usage: $0 <feature|fix|release> <name>" >&2
  exit 2
}

[ $# -eq 2 ] || usage
kind="$1"
name="$2"

case "$kind" in
  feature | fix | release) ;;
  *) usage ;;
esac

branch="$kind/$name"
worktree=".worktrees/$kind-$name"

git checkout develop
git pull --ff-only
mkdir -p .worktrees
git worktree add -b "$branch" "$worktree" develop
echo "Created worktree $worktree on branch $branch"
