#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Publish a feature/* or fix/* change branch to origin (set upstream).
# Refuses if the dedicated worktree has uncommitted changes.
# Usage: scripts/git-workflow/publish.sh <branch e.g. feature/foo>
set -eu

usage() {
  echo "Usage: $0 <branch e.g. feature/foo>" >&2
  exit 2
}

[ $# -eq 1 ] || usage
branch="$1"
worktree=".worktrees/$(printf '%s' "$branch" | tr '/' '-')"

case "$branch" in
  feature/* | fix/*) ;;
  *)
    echo "publish: branch '$branch' must be feature/<name> or fix/<name>." >&2
    exit 1
    ;;
esac

if ! git show-ref --verify --quiet "refs/heads/$branch"; then
  echo "publish: branch '$branch' does not exist." >&2
  exit 1
fi

if [ -d "$worktree" ]; then
  if [ -n "$(git -C "$worktree" status --porcelain)" ]; then
    echo "publish: worktree '$worktree' has uncommitted changes." >&2
    exit 1
  fi
fi

git push -u origin "$branch"
echo "Published $branch to origin (upstream set)."
