#!/usr/bin/env sh
# Generated by ai-coding-playbook — do not edit; regenerate via scripts/generate_rules.py
# Finish a classic Gitflow release: merge release/<version> into main, tag
# v<version>, merge back into develop, then remove the worktree and branch.
# Usage: scripts/git-workflow/release.sh <version>
set -eu

usage() {
  echo "Usage: $0 <version>" >&2
  exit 2
}

[ $# -eq 1 ] || usage
version="$1"
branch="release/$version"
worktree=".worktrees/release-$version"
tag="v$version"

if ! git show-ref --verify --quiet "refs/heads/$branch"; then
  echo "release: branch '$branch' does not exist." >&2
  exit 1
fi

if [ -d "$worktree" ]; then
  if [ -n "$(git -C "$worktree" status --porcelain)" ]; then
    echo "release: worktree '$worktree' has uncommitted changes." >&2
    exit 1
  fi
fi

git checkout main
git pull --ff-only
git merge --no-ff "$branch" -m "Merge branch '$branch'"
git tag -a "$tag" -m "Release $version"

git checkout develop
git pull --ff-only
git merge --no-ff "$branch" -m "Merge branch '$branch' into develop"

if [ -d "$worktree" ]; then
  git worktree remove "$worktree"
fi
git branch -d "$branch"

echo "Released $version (tag $tag). Merged into main and develop; cleaned up $branch."
